### PR TITLE
Add modules

### PR DESCRIPTION
**Pull request by kedhammar**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/seqinspector/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/seqinspector _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by kedhammar** [comment]
Addresses #8

**Comment by kedhammar** [comment]
> what's the usecase for clumpify again? Is it to produce more compressed fastqs or something else?

https://nf-co.re/modules/bbmap_clumpify

Main use case for us seems to be deduplication

**Comment by alneberg** [comment]
I would say skip clumpify at this point and maybe give a try to run fastp inside the main.nf as well? It should be ran for any file so fairly similar to fastqc I would imagine?

**Comment by Aratz** [comment]
fastp is used in nf-core/demultiplex, see here for inspiration: https://github.com/nf-core/demultiplex/blob/aa4d93673a4e04b1daf7b4bd71269d6054275534/workflows/demultiplex.nf#L199

**Pull request closed without merging**
