### PR TITLE
adding fastq_screen module

### PR DESCRIPTION
**Pull request by FranBonath**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/seqinspector/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/seqinspector _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by FranBonath** [comment]
@nf-core-bot fix linting, please :)

**Comment by MatthiasZepper** [comment]
I only had a quick glance (so no formal review yet), but I would prefer that we start using `git lfs` on this repo for managing the references and other large files. I am sure that we will have more modules that require large reference data:

```
git lfs install
git lfs track "*.bt2" 
git lfs track "*.fa" 
git add .gitattributes
git commit
```

Ideally, you would in the process also edit the history on your branch, because the previous commands would only apply to future files, but not the ones that you already committed. For this, it is necessary to rewrite the history and that will lead to diverging branches with your _origin_:

> On branch dev
> Your branch and 'origin/dev' have diverged,
> and have 1 and 1 different commits each, respectively.
>   (use "git pull" if you want to integrate the remote branch with yours)

Instead of pulling in the origin, however, (_which would bring back the data we want to prune from history_), we force push the rewritten history to the remote origin on GitHub. Then your origin dev branch is clean again and can be safely merged to the upstream repo in nf-core after approval of this PR:
```
git checkout -b "backup_dev"
git checkout dev
git lfs install
pip install git-filter-repo
git lfs migrate import --include="*.bt2"  --include="*.fa" 
git lfs track "*.bt2" 
git lfs track "*.fa" 
git add .
git commit --amend
git reflog expire --expire=now --single-worktree
git gc --prune=now --aggressive
git push --force-with-lease
```

**Comment by alneberg** [comment]
The suggestion by @MatthiasZepper seems to be a bit of work but I think I agree. Probably worth getting `git lfs` up and running right away.

**Comment by MatthiasZepper** [comment]
> The suggestion by @MatthiasZepper seems to be a bit of work but I think I agree. Probably worth getting `git lfs` up and running right away.

The downside of `git lfs` is, that it is not right away supported by Nextflow :-/ ... sounds like a good feature for a plugin but...alas.

**Comment by FranBonath** [comment]
As per our discussion in the dev meeting, we bench the `git lfs` implementation for now, right? An I will instead pivot to use iGenome references for the tests, correct? @alneberg @MatthiasZepper

**Comment by alneberg** [comment]
Yes, `git lfs` is not an option at the moment I think. If a suitable genome is already present in iGenomes that would be perfect I think.

**Comment by FranBonath** [comment]
I tried to provide the references for fastq screen test profile via igenomes, which is in a S3 bucket. Problem is, fastqscreen cannot read it. We have a few options, none I really like:

1. ) ship the pipeline with bowtie2build and make our own bowtie index. This is what the module test uses. I don't like it because we add a tool to our pipeline *just* so we get the tests to run. A tool that can break and that has no impact on actually running the pipeline for real
2. ) what I am currently doing and providing the reference as part of the module. We can chose for it to be only one, very small, references, for example PhiX. I hate hard coded anything.
3. ) don't have test :P

**Comment by FranBonath** [comment]
> I tried to provide the references for fastq screen test profile via igenomes, which is in a S3 bucket. Problem is, fastqscreen cannot read it. We have a few options, none I really like:
> 
> 1. ) ship the pipeline with bowtie2build and make our own bowtie index. This is what the module test uses. I don't like it because we add a tool to our pipeline _just_ so we get the tests to run. A tool that can break and that has no impact on actually running the pipeline for real
> 2. ) what I am currently doing and providing the reference as part of the module. We can chose for it to be only one, very small, references, for example PhiX. I hate hard coded anything.
> 3. ) don't have test :P



> I tried to provide the references for fastq screen test profile via igenomes, which is in a S3 bucket. Problem is, fastqscreen cannot read it. We have a few options, none I really like:
> 
> 1. ) ship the pipeline with bowtie2build and make our own bowtie index. This is what the module test uses. I don't like it because we add a tool to our pipeline _just_ so we get the tests to run. A tool that can break and that has no impact on actually running the pipeline for real
> 2. ) what I am currently doing and providing the reference as part of the module. We can chose for it to be only one, very small, references, for example PhiX. I hate hard coded anything.
> 3. ) don't have test :P

I had a lengthly discussion with @maxulysse about this, but we couldn't really agree.

**Comment by Aratz** [comment]
I'd say 2, if you choose a tiny reference. 

I think in general bad tests are better than no tests, I don't think it's such a big issue that the reference is unrealistically small, the tests will still catch eg if fastq_screen crashes because of some config error.

**Pull request closed without merging**
