### PR TITLE
add fq lint

### PR DESCRIPTION
**Pull request by erkutilaslan**
added barebones fq/lint module to the pipeline.
looking for feedback to how to implement it.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/seqinspector/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/seqinspector _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ctuni** [comment]
I see that the `fq` tool by default exits with an error if linting issues are found. I think that the way of using it in the pipeline should be instead to use the `--lint-mode log` ext.args always. That way the errors are logged and the user can read them instead of having the pipeline fail and exit if issues are found in the validation of FASTQ files

**Comment by sarahjeeeze** [comment]
Do you need to update the README.md

**Review by MatthiasZepper — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution!

Like with your other PR, you are missing a module config. Therefore, the tool lacks `ext.args` and a `publishDir` directive. Please see [this example from the rnaseq pipline](https://github.com/nf-core/rnaseq/blob/master/modules/nf-core/sortmerna/nextflow.config) for inspiration - but disregard the complex conditional logic. 

As a bare minimum, you should set the `--lint-mode log` as `ext.args`, otherwise the pipeline will crash upon encountering a single invalid read pair. Optionally, you can choose to pick [a lower validation level](https://github.com/stjude-rust-labs/fq?tab=readme-ov-file#validators) by default. 

I am somewhat undecided, whether the output should nonetheless be mixed into the MultiQC channel, although the tool is not supported.

**Comment by erkutilaslan** [comment]
Thanks a lot for the comments and suggestions! I have a question regarding the `publishDir`.
The `conf/modules.config` contains the following:
```
    publishDir = [
        path: { "${params.outdir}/${task.process.tokenize(':')[-1].tokenize('_')[0].toLowerCase()}" },
        mode: params.publish_dir_mode,
        saveAs: { filename -> filename.equals('versions.yml') ? null : filename }
    ]
```
Which creates a publishDir for fq/lint output. Should I still define the publishDir for the module separately as suggested?
If so if someone can explain the logic of the above part I would be grateful :)

**Pull request closed without merging**
